# Generated by Django 4.2.11 on 2024-04-12 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(1970, 1, 1, 0, 0)
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "not started"),
                    (1, "in progress"),
                    (2, "completed"),
                ],
                default=0,
            ),
        ),
    ]
